### ISSUE TITLE
[FR] Include semver outcome in outputs

### ISSUE THREAD

**Issue by alexeagle** [smlx/ccv#161]
I'd like to automate tagging of minor and patch releases.

However new major releases should have some devrel thought applied (for example, migration docs for breaking changes).
Also it's too easy to accept someone's PR without noticing a BREAKING CHANGE comment and accidentally ship a major release. This is bad since semver rules say you're now committed to that mistake.

At minimum it would be nice to have an output like `new-tag-major` that is true when the major version was incremented (https://github.com/smlx/ccv/blob/main/ccv.go#L119 )

**Comment by smlx** [comment]
How does #161 work for your use case, @alexeagle? It gives another output variable for the action that describes the type. For example:

```
new-tag=true
new-tag-version=v0.10.0
new-tag-version-type=minor
```

**Comment by alexeagle** [comment]
Yes that solves this very well, thank you!!
